---
label: default
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
- type: datetime
  name: publish_date
  label: Publish Date
  config:
    required: true
- name: seo
  type: include
  config: {}
  template: seo
  label: SEO
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
pages:
- contact.md
- resources.md
